### ISSUE TITLE
サボる doesn't seem to show up

### ISSUE THREAD

**Issue by Thermospore** [toasted-nutbread/yomichan-bccwj-frequency-dictionary#1]
Should be present on both long and short list
![image](https://user-images.githubusercontent.com/35350819/108701906-06633680-74b5-11eb-8b03-805721095d42.png)

**Comment by toasted-nutbread** [comment]
Should be fixed in [1.0.1](https://github.com/toasted-nutbread/yomichan-bccwj-frequency-dictionary/releases/tag/1.0.1).

**Comment by Thermospore** [comment]
Nice, seems to be working for me on Yomichan 21.1.31.1!
![image](https://user-images.githubusercontent.com/35350819/109454894-c266b900-7a01-11eb-9f13-f2ade3febe90.png)
![image](https://user-images.githubusercontent.com/35350819/109454775-761b7900-7a01-11eb-9f9d-e42a4a247c7b.png)
